repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: debug-statements
    -   id: check-toml
    -   id: check-yaml
        # Excluding the mkdocs.yml file due to it containing the following:
        #     !!python/name:pymdownx.superfences.fence_div_format
        # The YAML validator attempts to load this 'code' and fails, so we will
        # exclude the file from YAML checks.
        exclude: external-docs/mkdocs.yml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
