site_name: csvcubed
site_url: https://gss-cogs.github.io/csvcubed-docs/external
nav:
    - Home: 
      - index.md
    - Why: 
      - why/index.md
    - Quickstart: 
      - quick-start/index.md
      - Installation: quick-start/installation.md
      - Shaping your data: quick-start/shaping.md
    - Guides: 
      - guides/index.md
      - Raise an issue: guides/raise-an-issue.md
      - Shape your data: guides/shape-data.md
      - Errors:
        - guides/errors/index.md
        - Column validation: guides/errors/column-validation.md
        - Missing column definition: guides/errors/missing-column-definition.md
        - Column not found in data: guides/errors/column-not-found-in-data.md
        - Duplicate column title: guides/errors/duplicate-column-title.md
        - No dimensions defined: guides/errors/no-dimensions-defined.md
        - Wrong number components: guides/errors/wrong-number-components.md
        - CSV column literal with URI template: guides/errors/csv-column-literal-with-uri-template.md
        - CSV column URI template missing: guides/errors/csv-column-uri-template-missing.md
        - Neither defined: guides/errors/neither-defined.md
        - Observation values missing: guides/errors/observation-values-missing.md
        - Undefined values: guides/errors/undefined-values.md
        - Multiple measure columns: guides/errors/multiple-measure-columns.md
        - Multiple units columns: guides/errors/multiple-units-columns.md
        - Both measure types defined: guides/errors/both-measure-types-defined.md
        - Both unit types defined: guides/errors/both-unit-types-defined.md
        - Units not defined: guides/errors/units-not-defined.md
    - Reference Metadata: 
      - reference-metadata/index.md
    - Glossary: 
      - glossary/index.md
    - API Documentation: 
      - api-documentation/index.md
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    # - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
