site_name: csvcubed
site_url: https://gss-cogs.github.io/csvcubed-docs/external
nav:
    - Home: 
      - index.md
    - Why: 
      - why/index.md
    - Quickstart: 
      - quick-start/index.md
      - Installation: quick-start/installation.md
      - Shaping your data: quick-start/shaping.md
    - Guides: 
      - guides/index.md
      - Filing a bug: guides/file-bug.md
      - Shaping your data: guides/shaping-data.md
      - Errors:
        - guides/errors/index.md
        - Typical error: guides/errors/typical-error.md
    - Reference Metadata: 
      - reference-metadata/index.md
    - Glossary: 
      - glossary/index.md
    - API Documentation: 
      - api-documentation/index.md
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    # - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
