site_name: csvcubed
site_url: https://gss-cogs.github.io/csvcubed-docs/external
repo_url: https://github.com/GSS-Cogs/csvcubed
repo_name: GSS-Cogs/csvcubed
nav:
  - Home:
      - index.md
  - Quick start:
      - quick-start/index.md
      - Installation: quick-start/installation.md
      - Designing a CSV: quick-start/designing-csv.md
      - Building a CSV-W: quick-start/build.md
      - Describing your CSV: quick-start/describing-csv.md
      - Linking data: quick-start/linking-data.md
      - Inspecting a CSV-W: quick-start/inspect.md
  - Guides:
      - guides/index.md
      - Commands:
        - build: guides/command-line/build-command.md
        - code list build: guides/command-line/code-list-build-command.md
        - inspect: guides/command-line/inspect-command.md
        - Logging: guides/command-line/logging.md
      - Configuration:
        - guides/configuration/index.md
        - By convention: guides/configuration/convention.md
        - Explicit configuration:
          - guides/configuration/qube-config.md
          - Catalog metadata: guides/configuration/metadata.md
          - Column definitions: guides/configuration/column-definitions.md
          - Dimension configuration: guides/configuration/columns/dimensions.md
          - Observation configuration: guides/configuration/columns/observations.md
          - Measure configuration: guides/configuration/columns/measures.md
          - Unit configuration: guides/configuration/columns/units.md
          - Attribute configuration:
            - guides/configuration/columns/attributes.md
            - Resource attributes: guides/configuration/columns/attribute-resources.md
            - Literal attributes: guides/configuration/columns/attribute-literals.md
            - Attribute values: guides/configuration/columns/attribute-values.md
        - Templates: guides/configuration/templates.md
        - Measures: guides/configuration/measure-configuration.md
        - Units: guides/configuration/unit-configuration.md
        - Code Lists: guides/configuration/code-list-config.md
      - Shape your data:
        - guides/shape-data/index.md
        - Standard shape: guides/shape-data/standard-shape.md
        - Pivoted shape: guides/shape-data/pivoted-shape.md
        - Shape conversion: guides/shape-data/shape-conversion.md
      - Handling missing observed values: guides/missing-observed-values.md
      - Errors:
        - guides/errors/index.md
        - build command errors: guides/errors/build-command-errors/index.md
        - inspect command errors: guides/errors/inspect-command-errors/index.md
      - Linked Data:
        - Licenses: guides/linked-data/licenses.md
        - Organisations: guides/linked-data/organisations.md
        - Units: guides/linked-data/units.md
      - Raise an issue: guides/raise-issue.md
      - Working with URIs: guides/uris.md
      - Build with GitHub: guides/csv-to-csvw-github-action.md
  - Glossary:
      - glossary/index.md
theme:
  name: material
  features:
    - search.highlight
    - navigation.instant
    # - navigation.expand
#    - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - mermaid2
