[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.pyright]
pythonVersion="3.9"
exclude = [
    ".venv",
    "**/tests/behaviour/steps",
    "sharedmodels/scripts",
    "**/build"
]