[tool.poetry]
name = "pmd"
version = "0.1.0"
description = "Provides functionality necessary to transform RDF Data Cube style CSV-Ws into a format compatible with the Publish My Data platform. Part of the csvwlib family."
authors = ["Integrated Data Service - Dissemination <example@example.com>"]
license = "Apache-2.0"
exclude = ["docs/*", "pmd/tests/*"]

[tool.poetry.dependencies]
python = "^3.9"
rdflib = "*"
rdflib-jsonld = "==0.6.1"
requests = "*"
csvw = "*"
pandas = "*"
uritemplate = "*"
sharedmodels = {path = "./../sharedmodels", develop = true}
unidecode = "*"
pyparsing = "~=2.4.7" 

[tool.poetry.dev-dependencies]
devtools = {path = "./../devtools", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion="3.9"
exclude = [
    ".venv",
    "**/tests/behaviour/steps"
]