name: Build csvcubed
on:
  push


jobs:
  build_in_environments:
    strategy:
      matrix:
        python-version: ['3.9'] #, '3.10']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pyright
        run: npm install -g pyright

      - name: Install poetry
        run: pip install poetry

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ matrix.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install python packages
        run: poetry install

      - name: Run pyright
        run: poetry run pyright . --lib

      - name: Run unittests
        run: poetry run pytest --junitxml=pytest_results.xml

      - name: Upload unittests test results from xml file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-python${{ matrix.python-version }} unit test results
          path: pytest_results.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          check_name: ${{ matrix.os }}-python${{ matrix.python-version }} unit test results 
          junit_files: "pytest_results.xml"

      - name: Run behaviour tests
        run: poetry run behave tests/behaviour --tags=-skip --junit

      - name: Remove broken characters from xml test files
        # By removing broken characters from the xml unit/behave test files, we can then publish the tests results stored 
        # in those files in a user friendly way on github actions using 'EnricoMi/publish-unit-test-result-action@v1'.
        run: sed -i -e 's/[\x0A\x1B]//g' reports/TESTS-*.xml
          
      - name: Upload behave test results from xml files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-python${{ matrix.python-version }} behave test results 
          path: reports/*.xml

      - name: Publish Behave Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          check_name: ${{ matrix.os }}-python${{ matrix.python-version }} behave test results 
          junit_files: 'reports/*.xml'

      # todo: Need to build documentation and save it as an artifact
      # todo: Need to build python `.whl` package.

      # todo: iff in a release tag
      # todo: Need to publish the documentation to the github repo
      # todo: Need to publish the `.whl` package to pypi

      # todo: Ensure we only do Windows testing when in a release tag or is a commit on the main branch.
      # todo: Ensure we only do python3.9 testing in most cases, but also do python3.10 testing in all environments when in a release tag.

      # - name: Print versions on Windows
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     echo "Hello from Windows"
      #     python --version
      #     node --version
      #     pyright --version
      #     poetry --version
      #     poetry run csvcubed version
      #   shell: pwsh

      # - name: Print versions on Ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     echo "Hello from Ubuntu"
      #     python --version
      #     node --version
      #     pyright --version
      #     poetry --version
      #     poetry run csvcubed version
      #   shell: bash
