name: Test csvcubed on main branch push
on:
  push:
    branches:
      - main

jobs:
  test_in_environments:
    strategy:
      matrix:
        # Test on Windows + Ubuntu on oldest + newest supported versions of python.
        python-version: ['3.9', '3.11']
        pandas-version: ['pandas~2.0']
        os: [ubuntu-latest, windows-latest]
        #including a specific test case for testing older pandas version
        include:
          - os: ubuntu-latest
            python-version: 3.11
            pandas-version: pandas@^1.3
    uses: ./.github/workflows/reusable-test.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pandas-version: ${{ matrix.pandas-version }}

  build_package_and_documentation:
    if: needs.test_in_environments.result == 'success'
    needs: [test_in_environments]
    uses: ./.github/workflows/reusable-build.yaml

  publish_package_and_documentation:
    if: needs.build_package_and_documentation.result == 'success'
    needs: [build_package_and_documentation]
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
