name: Test csvcubed on pull request
on:
  pull_request:

jobs:
  test_in_environments:
    strategy:
      matrix:
        # Test on linux with the newest version of python and pandas 1.x/2.x.
        python-version: ['3.11']
        os: [ubuntu-latest, windows-latest]
        # Version lock pandas until v2.1.0 can be implemented without breaking Pyright
        # pandas-version: ['pandas@latest']
        pandas-version: ['pandas~2.0']
        include:
          # Test in Linux with Python 3.9
          - os: ubuntu-latest
            python-version: 3.9
          # Testing older pandas version
          - os: ubuntu-latest
            python-version: 3.11
            pandas-version: pandas@^1.3

    uses: ./.github/workflows/reusable-test.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pandas-version: ${{ matrix.pandas-version }}

  build_package_and_documentation:
    if: needs.test_in_environments.result == 'success'
    needs: [test_in_environments]
    uses: ./.github/workflows/reusable-build.yaml

  publish_package_and_documentation:
    if: needs.build_package_and_documentation.result == 'success'
    needs: [build_package_and_documentation]
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
