name: Test csvcubed on pull request
on:
  pull_request:

jobs:
  test_in_environments:
    strategy:
      matrix:
        # Test on linux with the newest version of python and pandas 1.x/2.x.
        python-version: ['3.11']
        os: [ubuntu-latest]
        pandas-version: ['pandas^1.3', 'pandas@latest']
        include:
          # Test in windows with the newest supported version of python.
          - os: windows-latest
            python-version: '3.11'
          # Test in Linux with Python 3.9
          - os: ubuntu-latest
            python-version: '3.9'

    uses: ./.github/workflows/reusable-test.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pandas-version: ${{ matrix.pandas-version }}
