name: Test csvcubed on pull request
on:
  pull_request:

jobs:
  test_in_environments:
    strategy:
      matrix:
        # Test on linux with the oldest and newest versions of python.
        python-version: ['3.9', '3.11']
        os: [ubuntu-latest]
        include:
          # Test in windows with the newest supported version of python.
          - os: windows-latest
            python-version: '3.11'

    uses: ./.github/workflows/reusable-test.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  test_in_windows:
    # strategy:
    #   matrix:
    #     python-version: ['3.9', '3.11']
    #     os: windows-latest

    uses: ./.github/workflows/reusable-test.yaml
    with:
      os: windows-latest
      python-version: '3.11'
