name: Release csvcubed
on:
  release:
    types: [published]
    
jobs:
  test_in_environments:
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/reusable/test-csvcubed.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
  
  build_package_and_documentation:
    if: needs.build_in_environments.result == 'success'
    needs: [test_in_environments]
    uses: ./.github/workflows/reusable/build-csvcubed.yaml

  publish_package_and_documentation:
    if: needs.build_package_and_documentation.result == 'success'
    needs: [build_package_and_documentation]
    uses: ./.github/workflows/reusable/deploy-csvcubed.yaml
    secrets: inherit