name: Trigger a workflow at gssutils that updates csvcubed package
on:
  # workflow_call:
  push:
    branches:
      - 'MuazzamChaud/issue527'

jobs:
  Trigger_gss-utils_workflow:
    runs-on: ubuntu-latest
    runs: gh workflow run updateCsvcubedPackage.yaml --repo github.com/GSS-Cogs/gss-utils
