name: Trigger a workflow at gssutils that updates csvcubed package
on:
  # workflow_call:
  push:
    branches:
      - 'MuazzamChaud/issue527'

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
  repository-projects: write

jobs:
  Trigger_gss-utils_workflow:
    name: Trigger_gss-utils_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: gh workflow run updateCsvcubedPackage.yaml --repo github.com/MuazzamChaud/gss-utils
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
