[tool.poetry]
authors = ["Integrated Data Service - Dissemination <example@example.com>"]
description = "A tool to generate RDF Data Cube style CSV-W cubes from tidy CSV files. Part of the csvcubed family."
exclude = ["docs/*"]
license = "Apache-2.0"
name = "csvcubed"
packages = [
  {include = "csvcubed"},
]
readme = "csvcubed/README.md"
version = "0.1.0"

[tool.poetry.dependencies]
pandas = "~=1.3.3"
pydantic = {git = "https://github.com/robons/pydantic.git", develop = true}
python = "~=3.9"
rdflib-jsonld = "==0.6.1"
csvcubed-models = "*"
pyparsing = "==2.4.7"

[tool.poetry.dev-dependencies]
csvcubed-devtools = "*"


[[tool.poetry.source]]
name = 'test-pypi'
secondary = true
url = 'https://test.pypi.org/simple/'

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.pyright]
exclude = [
  ".venv",
  "**/tests",
]
pythonVersion = "3.9"
